### ISSUE TITLE
.bcf to .otb error

### ISSUE THREAD

**Issue by Twix53791** [ctrlcctrlv/bitmapfont2otb#1]
I just git clone the repo and then I run the command `bitmapfont2otbTamsyn5x9b.pcfTamsyn5x9b.otb` and I get this error. Converting the same file to otf or ttf works fine.

```
Traceback (most recent call last):
  File "/usr/local/bin/bitmapfont2otb", line 48, in <module>
    out_ext[-1] = "f"
TypeError: 'str' object does not support item assignment
```

**Comment by ctrlcctrlv** [comment]
Sorry about that. I forgot to merge a commit I've had sitting on my HDD.
